name: Build .pyc file.

on:
  push:
    branches: [ "dev/main" ]
  pull_request:
    branches: [ "dev/main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[lint.skip]')"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build with compileall
      run: |
        python -m compileall . -l -o 2
    - name: Get latest commit hash
      id: get_hash
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ModLibrary-PYC-${{ steps.get_hash.outputs.sha_short }}
        path: __pycache__/
