name: Build (PR)
on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Python CI (PR)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    if: "!contains(github.event.head_commit.message, '[ci.skip]')"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4.5.0
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build
      run: |
        pyinstaller ModLibrary.spec -y
    - name: Get commit hash
      id: get_commit
      uses: pr-mpt/actions-commit-hash@v2
    - name: Upload build artifact.
      uses: actions/upload-artifact@v3.1.2
      with: 
        name: ModLibrary-${{ steps.get_commit.outputs.short }}-${{ matrix.os }}
        path: dist
