name: Python CI with cx_Freeze
on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci-windows-64:
    name: Python CI for Windows 64bit
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[ci.skip]')"
    steps: 
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4.5.0
      with:
        python-version: "3.11"
        architecture: "x64"
    - name: Install dependencies and build
      run: |
        pip install -r requirements.txt
        pip install cx_Freeze
        python setup.py build
    - name: Get commit hash
      id: get_commit
      run: echo "::set-output name=commit::$(git rev-parse --short HEAD)"
    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ModLibrary-build-win-64-${{ steps.get_commit.outputs.commit }}
        path: ./build/
  ci-windows-32:
    name: Python CI for Windows 32bit
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[ci.skip]')"
    steps: 
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4.5.0
      with:
        python-version: "3.11"
        architecture: "x86"
    - name: Install dependencies and build
      run: |
        pip install -r requirements.txt
        pip install cx_Freeze
        python setup.py build
    - name: Get commit hash
      id: get_commit
      run: echo "::set-output name=commit::$(git rev-parse --short HEAD)"
    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ModLibrary-build-win-32-${{ steps.get_commit.outputs.commit }}
        path: ./build/
